# general settings
name: DAGIR_RRDB_x1_lstm_32L_blind_visor96
model_type: DAGIRModel
scale: 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 42
debug: false

mix_degrade: true

# dataset and data loader settings
datasets:
  train:
    name: GIRTrain
    type: GIRTrainDataset
    dataroot_gt: ./datasets/degraded_imgs
    dataroot_lq: ./datasets/degraded_imgs
#    meta_info_file: ./data/meta_info/meta_info_WED_DIV2K_BSD_Flickr2k_train_all.txt
    meta_info_file: ./data/meta_info/meta_info_WED_DIV2K_BSD_Flickr2k_train_woHQ.txt
    io_backend:
      type: disk

    gt_size: 64
    use_flip: true
    use_rot: true
    degrade_type: all

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: GIRTrain
    type: GIRTrainDataset
    dataroot_gt: ./datasets/degraded_imgs
    dataroot_lq: ./datasets/degraded_imgs
    meta_info_file: ./data/meta_info/meta_info_WED_DIV2K_BSD_Flickr2k_val.txt
#    meta_info_file: ./data/meta_info/meta_info_WED_DIV2K_val10.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

# network structures
network_g:
  type: DynRRDN
  num_in_ch: 3
  num_feat: 64
  num_block: 12
  gc: 32
  res_scale: 1
  img_range: 255.0
  rgb_mean: [0.4488, 0.4371, 0.4040]
  kernel_size: 3
  weight_ratio: 0.5
#  attn: true
  blind: true


# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
#    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000]
    gamma: 0.5


  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 2e4
#  val_freq: !!float 10
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
#  print_freq: 10
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29600

find_unused_parameters: true
